### ISSUE TITLE
Vold and Custom Kernel

### ISSUE THREAD

**Issue by NeverSm1le** [null4n/vold-posix#7]
Looks like Vold doesn't work with custom kernel. I went the route of magisk => custom kernel => vold and upon restart, the phone asks for decryption pin.. it said correct but unable to decrypt data I was forced to reset phone. After that, the phone can't boot properly and I have to reflash the stock rom.

My phone: Mi A1, stock 8.1 november patch, custom kernel: moun kernel (https://forum.xda-developers.com/mi-a1/development/kernel-moun-kernel-los-aosp-t3771841), magisk v17.1.

Edit: comeback to 1.0 and it worked fine. Can you maintain both version 1.0 and 2.0 for people who use custom kernel like me? Thank you beforehand

**Comment by null4n** [comment]
Sorry for late reply.
This issue cause by MIUI or other thing. If 1.0 works for you then you can use it. For get up-to-date magiskinit, you need to do these setp
```
download newest zip and extract ``magisk_VER`` and ``common/service.sh``
place to $moddir, for magisk 18.0 it's /sbin/.magisk/img/vold-posix/
combine the 1.0 service.sh with the newest service.sh
reboot 2 times
```
It can't offer 2 version on magisk module repo. it will only pack the newest version automatically

**BTW, I don't suggest use 1.0 at all, that way will cause unknow issue, and why 1.0 will work on MIUI without decryption issue.**
